# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\pabst\PycharmProjects\Übungen\Tätigkeitsnachweis.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(658, 602)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 9, 601, 216))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.table_overview = QtWidgets.QTableWidget(self.layoutWidget)
        self.table_overview.setRowCount(2)
        self.table_overview.setObjectName("table_overview")
        self.table_overview.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.table_overview.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_overview.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_overview.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_overview.setHorizontalHeaderItem(3, item)
        self.table_overview.horizontalHeader().setDefaultSectionSize(80)
        self.table_overview.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.table_overview)
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 300, 331, 56))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(22)
        self.gridLayout_3.setVerticalSpacing(7)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.button_start_stop = QtWidgets.QPushButton(self.layoutWidget_2)
        self.button_start_stop.setCheckable(True)
        self.button_start_stop.setObjectName("button_start_stop")
        self.gridLayout_3.addWidget(self.button_start_stop, 1, 1, 1, 1)
        self.cb_workdays = QtWidgets.QComboBox(self.layoutWidget_2)
        self.cb_workdays.setObjectName("cb_workdays")
        self.gridLayout_3.addWidget(self.cb_workdays, 1, 0, 1, 1)
        self.button_add_day = QtWidgets.QPushButton(self.layoutWidget_2)
        self.button_add_day.setObjectName("button_add_day")
        self.gridLayout_3.addWidget(self.button_add_day, 1, 2, 1, 1)
        self.layoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 380, 231, 161))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.table_worktimes = QtWidgets.QTableWidget(self.layoutWidget_3)
        self.table_worktimes.setObjectName("table_worktimes")
        self.table_worktimes.setColumnCount(3)
        self.table_worktimes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_worktimes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_worktimes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_worktimes.setHorizontalHeaderItem(2, item)
        self.table_worktimes.horizontalHeader().setDefaultSectionSize(70)
        self.verticalLayout_3.addWidget(self.table_worktimes)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(250, 370, 261, 173))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(0, 4, -1, -1)
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setVerticalSpacing(16)
        self.gridLayout.setObjectName("gridLayout")
        self.edit_starttime = QtWidgets.QTimeEdit(self.groupBox)
        self.edit_starttime.setObjectName("edit_starttime")
        self.gridLayout.addWidget(self.edit_starttime, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 1, 1, 1)
        self.button_apply = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.button_apply.setFont(font)
        self.button_apply.setObjectName("button_apply")
        self.gridLayout.addWidget(self.button_apply, 2, 0, 1, 1)
        self.button_note = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.button_note.setFont(font)
        self.button_note.setObjectName("button_note")
        self.gridLayout.addWidget(self.button_note, 2, 2, 1, 1)
        self.button_add_worktime = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.button_add_worktime.setFont(font)
        self.button_add_worktime.setObjectName("button_add_worktime")
        self.gridLayout.addWidget(self.button_add_worktime, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.edit_endtime = QtWidgets.QTimeEdit(self.groupBox)
        self.edit_endtime.setObjectName("edit_endtime")
        self.gridLayout.addWidget(self.edit_endtime, 1, 1, 1, 1)
        self.button_delete = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.button_delete.setFont(font)
        self.button_delete.setObjectName("button_delete")
        self.gridLayout.addWidget(self.button_delete, 3, 2, 1, 1)
        self.display_duration = QtWidgets.QLineEdit(self.groupBox)
        self.display_duration.setReadOnly(True)
        self.display_duration.setObjectName("display_duration")
        self.gridLayout.addWidget(self.display_duration, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.layoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 240, 541, 48))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(24)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.edit_workpackage = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.edit_workpackage.setObjectName("edit_workpackage")
        self.gridLayout_2.addWidget(self.edit_workpackage, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.button_add_wp = QtWidgets.QPushButton(self.layoutWidget_4)
        self.button_add_wp.setObjectName("button_add_wp")
        self.gridLayout_2.addWidget(self.button_add_wp, 1, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 10)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 658, 21))
        self.menubar.setObjectName("menubar")
        self.menuDatei = QtWidgets.QMenu(self.menubar)
        self.menuDatei.setObjectName("menuDatei")
        self.menuBearbeiten = QtWidgets.QMenu(self.menubar)
        self.menuBearbeiten.setObjectName("menuBearbeiten")
        self.menuBericht = QtWidgets.QMenu(self.menubar)
        self.menuBericht.setObjectName("menuBericht")
        self.menuBerichte = QtWidgets.QMenu(self.menubar)
        self.menuBerichte.setObjectName("menuBerichte")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNeu = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\pabst\\PycharmProjects\\Übungen\\resources/file-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNeu.setIcon(icon)
        self.actionNeu.setObjectName("actionNeu")
        self.action_ffnen = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\pabst\\PycharmProjects\\Übungen\\resources/file-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ffnen.setIcon(icon1)
        self.action_ffnen.setObjectName("action_ffnen")
        self.actionSpeichern = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\pabst\\PycharmProjects\\Übungen\\resources/file-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSpeichern.setIcon(icon2)
        self.actionSpeichern.setObjectName("actionSpeichern")
        self.actionSpeichern_unter = QtWidgets.QAction(MainWindow)
        self.actionSpeichern_unter.setObjectName("actionSpeichern_unter")
        self.menuDatei.addAction(self.actionNeu)
        self.menuDatei.addAction(self.action_ffnen)
        self.menuDatei.addAction(self.actionSpeichern)
        self.menuDatei.addAction(self.actionSpeichern_unter)
        self.menubar.addAction(self.menuDatei.menuAction())
        self.menubar.addAction(self.menuBearbeiten.menuAction())
        self.menubar.addAction(self.menuBericht.menuAction())
        self.menubar.addAction(self.menuBerichte.menuAction())
        self.toolBar.addAction(self.actionNeu)
        self.toolBar.addAction(self.action_ffnen)
        self.toolBar.addAction(self.actionSpeichern)
        self.label_6.setBuddy(self.edit_endtime)
        self.label_7.setBuddy(self.display_duration)
        self.label_5.setBuddy(self.edit_starttime)
        self.label_2.setBuddy(self.edit_workpackage)

        self.retranslateUi(MainWindow)
        self.menubar.triggered['QAction*'].connect(MainWindow.open_recent_files)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tätigkeitsnachweis"))
        self.label.setText(_translate("MainWindow", "An diesen Arbeitspaketen wird gearbeitet"))
        item = self.table_overview.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Tätigkeit"))
        item = self.table_overview.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Anfang"))
        item = self.table_overview.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Ende"))
        item = self.table_overview.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Dauer"))
        self.label_3.setText(_translate("MainWindow", "Anzeigedatum"))
        self.button_start_stop.setText(_translate("MainWindow", "Beginn"))
        self.button_add_day.setText(_translate("MainWindow", "Hinzufügen"))
        self.label_4.setText(_translate("MainWindow", "gespeicherte Arbeitszeiten"))
        item = self.table_worktimes.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Startzeit"))
        item = self.table_worktimes.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Endezeit"))
        item = self.table_worktimes.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Dauer"))
        self.groupBox.setTitle(_translate("MainWindow", "Ändern"))
        self.label_6.setText(_translate("MainWindow", "Endezeit"))
        self.button_apply.setText(_translate("MainWindow", "Übernehmen"))
        self.button_note.setText(_translate("MainWindow", "Notiz"))
        self.button_add_worktime.setText(_translate("MainWindow", "Hinzufügen"))
        self.label_7.setText(_translate("MainWindow", "Dauer"))
        self.button_delete.setText(_translate("MainWindow", "Löschen"))
        self.label_5.setText(_translate("MainWindow", "Startzeit"))
        self.label_2.setText(_translate("MainWindow", "Tätigkeit"))
        self.button_add_wp.setText(_translate("MainWindow", "Hinzufügen"))
        self.menuDatei.setTitle(_translate("MainWindow", "Datei"))
        self.menuBearbeiten.setTitle(_translate("MainWindow", "Bearbeiten"))
        self.menuBericht.setTitle(_translate("MainWindow", "Ansicht"))
        self.menuBerichte.setTitle(_translate("MainWindow", "Berichte"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionNeu.setText(_translate("MainWindow", "Neu"))
        self.action_ffnen.setText(_translate("MainWindow", "Ö&ffnen..."))
        self.actionSpeichern.setText(_translate("MainWindow", "Speichern"))
        self.actionSpeichern_unter.setText(_translate("MainWindow", "Speichern unter..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
